name: Cache Dependencies
description: 'Caches Yarn dependencies with two-level strategy'
author: 'gratisv'

branding:
  icon: 'archive'
  color: 'purple'

inputs:
  enable-cache:
    description: 'Enable dependency caching'
    required: false
    default: 'true'

  yarn-cache-dir:
    description: 'Yarn cache directory path'
    required: true

  node-version:
    description: 'Node.js version (for cache key)'
    required: false
    default: 'latest'

  yarn-version:
    description: 'Yarn version (for cache key)'
    required: false
    default: 'latest'

outputs:
  cache-hit:
    description: 'Whether cache was restored (true/false)'
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Cache Yarn dependencies
      id: cache-deps
      if: inputs.enable-cache == 'true'
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ${{ inputs.yarn-cache-dir }}
          node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ inputs.yarn-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ inputs.yarn-version }}-
          ${{ runner.os }}-node-${{ inputs.node-version }}-
          ${{ runner.os }}-

    - name: Cache status
      if: inputs.enable-cache == 'true'
      shell: bash
      run: |
        if [[ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]]; then
          echo "✅ Cache restored successfully"
        else
          echo "⚠️ Cache not found, will install from scratch"
        fi
