name: Setup Node.js
description: 'Installs and configures Node.js'
author: 'gratisv'

branding:
    icon: 'download'
    color: 'green'

inputs:
    node-version:
        description: 'Node.js version to install'
        required: false
        default: 'latest'

outputs:
    node-version:
        description: 'Installed Node.js version'
        value: ${{ steps.setup-node.outputs.node-version }}

runs:
    using: composite
    steps:
        - name: Setup Node.js
          id: setup-node
          uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
          with:
              node-version: ${{ inputs.node-version }}

        - name: Verify Node.js installation
          shell: bash
          run: |
              node_version=$(node --version)
              echo "✅ Node.js installed: $node_version"
